#!/bin/bash

nodes=`sinfo --format="%N" --noheader`

print_usage () {
  cat << EOM
Usage: $0 [-n charles[01-19]]
    Get information about all jobs on specified nodes (defaults to all jobs)
Arguments
    -n    (optional) specify nodes, either comma separated list, or summarised.
          Mirrors slurm command -n usage in sinfo, and -w usage for squeue." 
 
EOM
}

while getopts 'n:' flag; do
  case "${flag}" in
    n) nodes="${OPTARG}" ;;
    *) print_usage
       exit ;;
  esac
done

squeue --nodelist=${nodes} -o"%i" --noheader | xargs -I {} sh -c 'scontrol show JobId={}'
